### ISSUE TITLE
api.byi.pw访问不了了

### ISSUE THREAD

**Issue by sy-records** [jerrybendy/get_favicon#10]
![image](https://user-images.githubusercontent.com/33931153/90840873-c304ff80-e38d-11ea-91ee-f296685bdf2c.png)

**Comment by jerrybendy** [comment]
被我停掉了。本来就是免费给大家用的东西，又不盈利，但总是有一堆人大批量刷接口，导致服务器不堪重负。像下图中这种没有 Reffer、没有 UA，并且请求体非常大的请求，特别多。

![image](https://user-images.githubusercontent.com/7897384/90844260-19763c00-e396-11ea-97e0-54359535a5eb.png)
