### ISSUE TITLE
这里有2种情况拿不到favicon

### ISSUE THREAD

**Issue by kangfenmao** [jerrybendy/get_favicon#8]
https://api.byi.pw/favicon/?url=nodejs.cn
https://api.byi.pw/favicon/?url=www.topit.me

第一种是在head内link中写的
第二种可直接访问domain/favicon.ico获取

**Comment by kangfenmao** [comment]
可供参考：https://www.npmjs.com/package/get-favicons

**Comment by jerrybendy** [comment]
这两种方式都是支持的。代码里面首先会检查 `head` 部分是否有 favicon 的定义，如果有就会返回；否则就去域名下面去找名为 `favicon.ico` 的文件。

**Comment by kangfenmao** [comment]
https://api.byi.pw/favicon/?url=www.topit.me
http://www.topit.me/favicon.ico

这两种方式得到的结果是不同的 @jerrybendy

**Comment by kangfenmao** [comment]
有兴趣可以看看我做的这个开源项目，里面用到了你提供的服务：
https://shuqian.pro/

**Comment by jerrybendy** [comment]
这个项目是一套 PHP 的实现。类似地，我也写了一套 Nodejs 的实现。但目前 `api.byi.pw` 网站上是代理的 google 的数据，并添加了一层缓存。所以其实是没有使用这套实现方案的。
