### ISSUE TITLE
https://api.byi.pw 域名https证书异常

### ISSUE THREAD

**Issue by cong-min** [jerrybendy/get_favicon#9]
https://api.byi.pw 这个域名的ssl证书在chrome上会显示为 “您的连接不是私密连接”（Safari上正常）
有看到是签发了 Let's Encrypt 的泛域名ssl证书，并没有过期。
但估计是引用证书的方式不太正确？请检查一下

**Comment by cong-min** [comment]
有可能是域名权限没有验证成功，签发的证书不完整？（猜测）

**Comment by jerrybendy** [comment]
我刚刚试了一下是好的（Chrome 69），你 ping 一下 api.byi.pw 看是哪个 IP

**Comment by cong-min** [comment]
Chrome 版本 Mac-69.0.3497.100（正式版本） （64 位）
Ping 出来的IP地址：106.15.189.1
证书异常的截图：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11243798/46917870-386b5080-cffe-11e8-9535-b3ad27dc343e.png">

**Comment by jerrybendy** [comment]
我又试了一下，包括 FireFox 及 Chrome 隐身模式等，而且确定网络请求是这个 IP，确实是好的，没有遇到你所说的这个问题……

**Comment by cong-min** [comment]
我的 FireFox 及 Chrome。及其隐身模式都不行... 另一台设备的也是。
Safari是都正常..
手机上又是一切正常的...

**Comment by jerrybendy** [comment]
是不是你的操作系统或浏览器没有信任 Let's Encrypt 的根证书呢？
